Style/Documentation:
  Enabled: false

Metrics/LineLength:
  Max: 100

Metrics/MethodLength:
  Max: 25

Metrics/BlockLength:
  Max: 25

AllCops:
  TargetRubyVersion: 2.6

Metrics/AbcSize:
  Max: 50

Style/AsciiComments:
  Enabled: false

Style/ClassVars:
  Enabled: false

Style/IdenticalConditionalBranches:
  Enabled: false

Lint/Void:
  Enabled: false

Lint/ShadowingOuterLocalVariable:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/PerceivedComplexity:
  Max: 20

Metrics/ClassLength:
  Max: 300